version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception
    restart: always
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - .env

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
  mariadb_data:
